server:
  port: 5174

spring:
  jpa:
    database-platform: com.clankalliance.backbeta.sqlite.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  redis:
    host: 127.0.0.1
    port: 5175
tencentCloud:
  sms:
    secretId:
    secretKey:
    appId:
    appKey:
    signName:
    templateId:
    expireTime:
  captcha:
    captchaAppId:
    appSecretKey: 
  ip: 
clankToken:
  statusExpireTime: 43200000
  phoneExpireTime: 4320000
